backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
site_url: https://dorianeolivier.fr

collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Projets" # Used in the UI
    label_singular: "Projet" # Used in the UI, ie: "New Post"
    folder: "contents" # The path to the folder where the documents are stored
    format: "json"
    create: true # Allow users to create new documents in this collection
    slug: "{{category}}-{{title}}.json" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "project/{{title}}"
    # editor:
    #   preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Catégorie",
        name: "category",
        widget: "select",
        options: ["3d", "oldschool", "charadesign", "illustration"],
        hint: "La catégorie de ton projet."
      }
      - { label: "Titre", name: "title", widget: "string", hint: "Le titre de ton projet."}
      - { label: "Vidéo ?", name: "isVideo", widget: "boolean", default: false, hint: "Ton projet est une vidéo ? Sélectionne moi."}
      - {
          label: "Thumbnail Vidéo",
          name: "thumbnail",
          widget: "file",
          default: null,
          required: false,
          hint: "La thumbnail de ton projet vidéo qui sera affiché dans la catégorie correspondante (seulement si ton projet est une vidéo)."
        }
      - { label: "Image/Vidéo du projet", name: "src", widget: "file", default: null, hint: "L'image correspondant à ton projet." }
      - {label: 'Date du projet',
      name: 'date',
      widget: 'string',
      hint: "La date à laquelle tu as créé ton projet. Essaie de garder toujours le même format. (ex: Février 2019)"
      }
      - { label: "Type de projet", name: "type", widget: "string", default: "", hint: "Projet personnel, projet scolaire, freelance..."}
      - { label: "Techniques utilisées", name: "technique", widget: "string", default: "", hint: "Peinture à l'huile, Maya, Stop Motion..."}
      - { label: "Description", name: "description", widget: "text", hint: "Le pourquoi du comment, c'est ici que tu peux raconter ta vie."}